apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: helm.sh/hook
kind: HelmRelease
metadata:
  name: argocd
spec:
  chart:
    repository: https://argoproj.github.io/argo-helm
    name: argo-cd
